name: GameShell CI
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-26.04, ubuntu-24.04, ubuntu-22.04, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout the GameShell repo
        uses: actions/checkout@v4
      - if: ${{ startsWith(matrix.platform, 'ubuntu') }}
        name: Install Linux deps
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --assume-yes \
            gettext man-db psmisc procps nano tree ncal zsh
      # - if: ${{ matrix.platform == 'macos-latest' }}
      #   name: Install macOS deps
      #   run: |
      #     brew install coreutils pstree tree man-db
      - name: Run the tests
        run: |
            make tests-bash && make tests-zsh
